//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by ts_odbc.rc
//
#define IDS_BADDSN 1
#define IDS_MSGTITLE 2
#define IDOK2 3
#define IDC_TEST 4
#define IDC_PASSWORD_STATIC 4
#define IDC_SSL_STATIC 4
#define IDC_HOST_VER_STATIC 5
#define IDC_DSNAME 400
#define IDC_DSNAMETEXT 401
#define IDC_DESC 404
#define IDC_FETCH_SIZE_STATIC 404
#define IDC_SERVER 407
#define IDC_NOTICE_USER 414
// TODO: Create IDS macro for new authentication method(s)
#define IDS_AUTHTYPE_DEFAULT 416
#define IDS_LOGTYPE_OFF 420
#define IDS_LOGTYPE_FATAL 421
#define IDS_LOGTYPE_ERROR 422
#define IDS_LOGTYPE_WARNING 423
#define IDS_LOGTYPE_INFO 424
#define IDS_LOGTYPE_DEBUG 425
#define IDS_LOGTYPE_TRACE 426
#define IDS_LOGTYPE_ALL 427
#define DLG_CONFIG 1001
#define IDC_PORT 1002
// TODO: Create IDS macro (+ _STATIC macro) for new authentication parameters
#define IDC_USER 1006
#define IDC_PASSWORD 1009
#define IDC_MANAGEDSN 1077
#define IDC_EDIT1 1112
#define IDC_CONNTIMEOUT_STATIC 1112
#define IDC_REQUEST_TIMEOUT_STATIC 1112
#define IDC_CHECK1 1113
#define IDC_CONNECTION_TIMEOUT_STATIC 1113
#define IDC_CHECK2 1114
#define IDC_USESSL 1114
#define IDC_COMBO1 1115
#define IDC_AUTHTYPE 1115
#define IDC_HOST_VER 1115
#define IDC_USERNAME_STATIC 1116
#define IDC_MAX_CONNECTIONS_STATIC 1116
#define IDC_MAX_RETRY_COUNT_CLIENT_STATIC 1117
#define IDC_AUTH_STATIC 1123
#define ID_ADVANCED_OPTIONS 1124
#define ID_LOG_OPTIONS 1125
#define IDC_DRIVER_VERSION 1126
#define IDC_AUTH_SETTINGS 1127
#define IDC_CONN_SETTINGS 1128
#define DLG_ADVANCED_OPTIONS 1129
#define IDC_REQUEST_TIMEOUT 1130
#define DLG_LOG_OPTIONS 1131
#define IDC_FETCH_SIZE 1131
#define IDC_LOG_LEVEL 1132
#define IDC_CONNECTION_TIMEOUT 1132
#define IDC_LOG_PATH 1133
#define IDC_MAX_CONNECTIONS 1133
#define IDC_MAX_CONNECTIONS2 1134
#define IDC_MAX_RETRY_COUNT_CLIENT 1134
#define IDC_BROWSE_BTN 1150

// Next default values for new objects
//
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE 113
#define _APS_NEXT_COMMAND_VALUE 40001
#define _APS_NEXT_CONTROL_VALUE 1136
#define _APS_NEXT_SYMED_VALUE 101
#endif
#endif
