name: Automatic Code Reviews

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: shenxianpeng/cpp-linter-action@master
      id: review
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}      
      with:
        version: 10
        style: file
      continue-on-error: true
